// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { CdklabsTypeScriptProject } from 'cdklabs-projen-project-types';
import {
    ArrowParens,
    EndOfLine,
    PrettierOptions,
    QuoteProps,
    TrailingComma
} from 'projen/lib/javascript';

/**
 * Configures linting settings for the project for tools such as Prettier,
 * ESLint, and Husky.
 */
export const configureLinting = (project: CdklabsTypeScriptProject) => {
    /** Prettier */
    project.addFields({
        'lint-staged': {
            '**/*': ['prettier --write --ignore-unknown']
        }
    });

    project.addScripts({
        prepare: 'husky'
    });

    project.eslint?.allowDevDeps('esbuild.ts');
    project.eslint?.allowDevDeps('vitest.config.ts');
    project.eslint?.allowDevDeps('**/handler/**/*.ts');
    project.eslint?.allowDevDeps('**/utilities/**/*.ts');
    project.eslint?.allowDevDeps('src/common/lambda/**/*.ts');

    project.eslint?.addRules({
        '@typescript-eslint/no-require-imports': 'off'
    });

    const autoGeneratedFiles = [
        '.projen/*.json',
        '.eslintrc.json',
        '.prettierrc.json',
        'API.md',
        'package.json',
        'tsconfig.dev.json',
        'yarn.lock'
    ];

    autoGeneratedFiles.forEach((f) => {
        project.eslint?.addIgnorePattern(f);
        project.prettier?.addIgnorePattern(f);
    });
};

export const prettierOptions: PrettierOptions = {
    settings: {
        tabWidth: 4,
        useTabs: false,
        semi: true,
        singleQuote: true,
        quoteProps: QuoteProps.ASNEEDED,
        trailingComma: TrailingComma.NONE,
        bracketSpacing: true,
        arrowParens: ArrowParens.ALWAYS,
        endOfLine: EndOfLine.LF
    },
    overrides: [
        {
            files: ['*.yml', '*.yaml'],
            options: {
                singleQuote: false,
                tabWidth: 2
            }
        },
        {
            files: ['*.md'],
            options: {
                tabWidth: 1
            }
        }
    ]
};
